import json
from difflib import SequenceMatcher

import chromadb
from chromadb.utils import embedding_functions
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

# --- Configuration & Paths ---
DB_PATH = "./swift_vec_db"           # Directory where ChromaDB reads local vector data files
COLLECTION_NAME = "taylor_lyrics"    # Target database collection to execute queries against
MODEL_NAME = "all-MiniLM-L6-v2"      # Transformer model matching the original ingestion configuration
OPENAI_MODEL = "gpt-4o-mini"         # OpenAI model optimized for query generation and metadata reranking

openai_client = OpenAI()


# Use Gestalt Pattern Matching to calculate string similarity ratios and eliminate near-duplicate text
def too_similar(a, b, threshold=0.82):
    return SequenceMatcher(None, a, b).ratio() >= threshold


# Leverage OpenAI to generate a multi-faceted semantic search matrix from a single user input
def expand_query(query):
    prompt = f"""
User situation:
{query}

Create 6 short search queries that capture different emotional interpretations
of this situation for matching Taylor Swift songs/lyrics.

Avoid just repeating the same words. Include themes like leaving, moving on,
resentment, heartbreak, relief, betrayal, denial, choosing yourself, etc. only
if relevant.

Return JSON only:
{{
  "queries": ["query 1", "query 2", "query 3"]
}}
"""

    response = openai_client.chat.completions.create(
        model=OPENAI_MODEL,
        response_format={"type": "json_object"},
        messages=[
            {
                "role": "system",
                "content": "You create concise semantic search queries. Return valid JSON only."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.4  # Moderate temperature allows creative variation without losing semantic focus
    )

    data = json.loads(response.choices[0].message.content)
    queries = data.get("queries", [])

    # Always preserve the user's literal input as the primary query vector
    return [query] + [q for q in queries if q and q != query]


# Execute vector similarity searches while enforcing diversity constraints to prevent track clustering
def query_diverse(collection, query, final_k=8, fetch_k=25):
    results = collection.query(
        query_texts=[query],
        n_results=fetch_k,
        include=["documents", "metadatas", "distances"]
    )

    filtered = []
    seen_songs = set()

    for doc, meta, distance in zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0]
    ):
        song_key = meta["song"]

        # Diversity Filter A: Prevent a single track from occupying multiple slots in the retrieval pool
        if song_key in seen_songs:
            continue

        # Diversity Filter B: Eliminate nearly identical lyric chunks across different dataset sections
        if any(too_similar(doc, kept["document"]) for kept in filtered):
            continue

        filtered.append({
            "document": doc,
            "metadata": meta,
            "distance": distance,
            "source_query": query
        })

        seen_songs.add(song_key)

        if len(filtered) == final_k:
            break

    return filtered


# Execute parallel sweeps using query matrix, then consolidate unique matches
def retrieve_candidates(collection, query, per_query_k=8, fetch_k=25):
    expanded_queries = expand_query(query)
    all_matches = []

    print("Expanded queries:")
    for q in expanded_queries:
        print(f"- {q}")

    # Gather search pools across every thematic variation generated by the LLM
    for q in expanded_queries:
        all_matches.extend(
            query_diverse(
                collection,
                query=q,
                final_k=per_query_k,
                fetch_k=fetch_k
            )
        )

    unique = []
    seen_docs = set()
    seen_songs = set()

    # Consolidate, deduplicate, and enforce strict single-track limits on final candidate array
    for match in all_matches:
        meta = match["metadata"]
        doc = match["document"]
        song_key = meta["song"]

        if doc in seen_docs:
            continue

        if song_key in seen_songs:
            continue

        if any(too_similar(doc, kept["document"]) for kept in unique):
            continue

        unique.append(match)
        seen_docs.add(doc)
        seen_songs.add(song_key)

    return unique


# Use LLM to evaluate narrative perspective and score candidate relevance
def rerank_matches(query, matches, final_k=5):
    candidates = []

    # Map database metadata structures into an explicit context packet for evaluation
    for i, match in enumerate(matches):
        meta = match["metadata"]

        candidates.append({
            "index": i,
            "song": meta["song"],
            "album": meta["album"],
            "section": meta["section"],
            "themes": meta.get("themes", ""),
            "moods": meta.get("moods", ""),
            "situations": meta.get("situations", ""),
            "perspective": meta.get("perspective", ""),
            "speaker_role": meta.get("speaker_role", ""),
            "relationship_stage": meta.get("relationship_stage", ""),
            "summary": meta.get("summary", ""),
            "lyrics": match["document"],
            "distance": match["distance"],
            "source_query": match.get("source_query", "")
        })

    prompt = f"""
User situation:
{query}

Rank these Taylor Swift lyric candidates by how well they match the user's situation.

Important:
- Prioritize emotional/contextual fit, not keyword overlap.
- Strongly prioritize matching narrative perspective.
- If the user is the betrayed partner, a song from the cheating partner's POV should score lower.
- If the user wants to leave, prefer songs from the perspective of leaving, choosing yourself, or ending things.
- Do NOT reward candidates just because they contain words like break, heart, love, boyfriend, cry, cheated, or leave.
- Consider song profile fields: themes, moods, situations, perspective, speaker_role, relationship_stage, and summary.
- Consider lyrics too, but do not blindly match literal words.
- Be harsh. If a candidate is only vaguely related, score it 5 or lower.
- A 9 or 10 should feel like a genuinely strong match to the user's actual situation.

Return JSON only in this exact format:
{{
  "rankings": [
    {{
      "index": 0,
      "score": 8,
      "reason": "short explanation"
    }}
  ]
}}

Candidates:
{json.dumps(candidates, indent=2)}
"""

    response = openai_client.chat.completions.create(
        model=OPENAI_MODEL,
        response_format={"type": "json_object"},
        messages=[
            {
                "role": "system",
                "content": "You are a strict reranker for emotional song/lyric matching. Return valid JSON only."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0  # Temperature 0 enforces absolute analytical consistency for scoring operations
    )

    data = json.loads(response.choices[0].message.content)
    rankings = data["rankings"]
    
    # Sort candidates based on scores assigned by API
    rankings = sorted(rankings, key=lambda x: x["score"], reverse=True)

    reranked = []

    # Map top-scoring references back to original database arrays
    for item in rankings[:final_k]:
        idx = item["index"]

        if idx < 0 or idx >= len(matches):
            continue

        match = matches[idx].copy()
        match["rerank_score"] = item["score"]
        match["reason"] = item["reason"]
        reranked.append(match)

    return reranked


# Parse, layout, and print the final evaluation structures
def print_matches(matches):
    for match in matches:
        meta = match["metadata"]

        print("=" * 50)
        print(f"Score: {match['rerank_score']}/10")
        print(f"Distance: {match['distance']}")
        print(f"Song: {meta['song']}")
        print(f"Album: {meta['album']}")
        print(f"Section: {meta['section']}")
        print(f"Speaker role: {meta.get('speaker_role', '')}")
        print(f"Relationship stage: {meta.get('relationship_stage', '')}")
        print(f"Why: {match['reason']}")

        if meta.get("summary"):
            print(f"Song summary: {meta['summary']}")

        print()
        print(match["document"])


def main():
    # Initialize localized database client and load persistent vector targets
    chroma_client = chromadb.PersistentClient(path=DB_PATH)

    # Initialize Transformer embedding mechanism matching your original dataset matrix
    embedding_func = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name=MODEL_NAME
    )

    # Target active dataset collection bucket
    collection = chroma_client.get_or_create_collection(
        name=COLLECTION_NAME,
        embedding_function=embedding_func
    )

    # Execute search using a complex, implicit emotional scenario
    query = "I'm tired of being walked all over, I'm rebranding myself as someone who calls out bad behavior"

    candidates = retrieve_candidates(
        collection,
        query=query,
        per_query_k=8,
        fetch_k=30
    )

    print(f"\nRetrieved {len(candidates)} unique candidates.\n")

    # Run cross-evaluation to generate the final prioritized result recommendations
    reranked = rerank_matches(
        query=query,
        matches=candidates,
        final_k=5
    )

    print_matches(reranked)


if __name__ == "__main__":
    main()